name: yu_gi_oh_app
description: "A yu-gi-oh simple application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.7
  widget_zoom: ^0.0.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Matrix-book
      fonts:
        - asset: assets/fonts/Yu-Gi-Oh-Matrix-Book.ttf

    - family: Stone-Serif
      fonts:
        - asset: assets/fonts/Stone-Serif.ttf
